### ISSUE TITLE
Add iceweasel and icedove

### ISSUE THREAD

**Issue by arkhan** [funtoo/ports-2012#15]
Hello, it's posible to add iceweasel and icedove

Thanks

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2920

**Comment by arkhan** [comment]
Cool thanks
